name: Entrega 4 - SAST Alternativo (Semgrep)

on:
  workflow_dispatch:

jobs:
  semgrep-scan:
    name: Semgrep PHP Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        uses: docker://returntocorp/semgrep:latest
        with:
          args: scan --config=p/php --text --output=reporte-semgrep.txt .
        continue-on-error: true

      - name: Show Report in Logs
        run: cat reporte-semgrep.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: evidencia-semgrep-sast
          path: reporte-semgrep.txt